imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: random_background.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi: ~
    #translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets:
        json_manifest_path: '%kernel.project_dir%/public/assets/manifest.json'
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes: ['bootstrap_3_layout.html.twig']
    globals:
        siteNoticeText: '%app.notice.text%'
        siteNoticeStyle: '%app.notice.style%'

# Doctrine Configuration
doctrine:
    dbal:
        connections:
            eventmetrics:
                driver:   pdo_mysql
                host:     "%database.host%"
                port:     "%database.port%"
                dbname:   "%database.name%"
                user:     "%database.user%"
                password: "%database.password%"
                charset:  UTF8
            centralauth:
                driver:   pdo_mysql
                host:     "%database.replica.host%"
                port:     "%database.replica.port%"
                dbname:   "centralauth_p"
                user:     "%database.replica.user%"
                password: "%database.replica.password%"
                charset:  UTF8
            meta:
                driver:   pdo_mysql
                host:     "%database.replica.host%"
                port:     "%database.replica.port%"
                dbname:   "meta_p"
                user:     "%database.replica.user%"
                password: "%database.replica.password%"
                charset:  UTF8
            replicas:
                driver:   pdo_mysql
                host:     "%database.replica.host%"
                port:     "%database.replica.port%"
                dbname:   "%database.replica.name%"
                user:     "%database.replica.user%"
                password: "%database.replica.password%"
                charset:  UTF8

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        default_entity_manager: eventmetrics
        entity_managers:
            eventmetrics:
                connection: eventmetrics
                mappings:
                    model:
                        type: annotation
                        dir: '%kernel.root_dir%/../src/AppBundle/Model'
                        prefix: AppBundle\Model
                        alias: Model
                        is_bundle: false
            centralauth:
                connection: centralauth
                naming_strategy: doctrine.orm.naming_strategy.underscore
            replicas:
                connection: replicas
                naming_strategy: doctrine.orm.naming_strategy.underscore
            meta:
                connection: meta
                naming_strategy: doctrine.orm.naming_strategy.underscore

doctrine_migrations:
    dir_name: "%kernel.root_dir%/DoctrineMigrations"
    namespace: Application\Migrations
    table_name: migration_versions
    name: Application Migrations
    organize_migrations: false

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer.transport%'
    host: '%mailer.host%'
    username: '%mailer.user%'
    password: '%mailer.password%'
    spool: { type: memory }

eight_points_guzzle:
    # (de)activate logging/profiler; default: %kernel.debug%
    logging: true

    clients:
        commons:
            base_url: "https://commons.wikimedia.org/w/api.php"

            # guzzle client options (full description here: https://guzzle.readthedocs.org/en/latest/request-options.html)
            options:
                headers:
                    Accept: "application/json"
                timeout: 30

sensio_framework_extra:
    router:
        annotations: false

toolforge:
    oauth:
        consumer_key: '%oauth.key%'
        consumer_secret: '%oauth.secret%'
        logged_in_user: '%app.logged_in_user%'
    intuition:
        domain: 'eventmetrics'

monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: critical
            handler: main_handler
        main_handler:
            type: group
            members: [console, log_file, mailer]
        console:
            type: console
            level: debug
            process_psr_3_messages: false
        log_file:
            type: stream
            level: info
            path: '%kernel.logs_dir%/%kernel.environment%.log'
        mailer:
            type: deduplication
            handler: swift
        swift:
            type: swift_mailer
            level: critical
            from_email: '%mailer.from_email%'
            to_email: '%mailer.to_email%'
            subject: 'EventMetrics error: %%message%%'
            formatter: monolog.formatter.html
            content_type: text/html
